[Journal]
# Maksymalny rozmiar logów systemowych
SystemMaxUse=200M
# Maksymalny rozmiar logów runtime (tmpfs, np. kontenery)
RuntimeMaxUse=50M
# Retencja - trzymamy logi max 1 miesiąc
MaxRetentionSec=1month
# Rotacja - pojedynczy plik do 50 MB
SystemMaxFileSize=50M
